sudo: false
notifications:
  email: false

os: linux
dist: focal
cache:
  directories:
    - $HOME/.cache/pip

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  # FIXME: Change to "3.10", Travis doesn't provide it yet...
  - "3.10.0"
  - "pypy3"

matrix:
  fast_finish: true

install:
  - pip install tox-travis codecov

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov
