sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  matrix:
    - ATTRS="true"
    - ATTRS="false"
install: pip install tox-travis codecov
script: tox
after_success: codecov