sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.4"
      env: TOXENV=py34-cython
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.5"
      env: TOXENV=py35-cython
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=py36-cython
    - python: "3.7"
      env: TOXENV=py37
      sudo: required
      dist: xenial
    - python: "3.7"
      env: TOXENV=py37-cython
      sudo: required
      dist: xenial
    - python: "pypy3.5-6.0.0"
      env: TOXENV=pypy35
    - python: "pypy3.5-6.0.0"
      env: TOXENV=pypy35-cython

    # Prevent breakage by a new releases
    - python: "3.6-dev"
      env: TOXENV=py36
    - python: "3.6-dev"
      env: TOXENV=py36-cython
    - python: "3.7-dev"
      env: TOXENV=py37
    - python: "3.7-dev"
      env: TOXENV=py37-cython

    # Meta
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=manifest
    - python: "3.6"
      env: TOXENV=docs

  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
