sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.5"
      env: TOXENV=py35-cython
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=py36-cython
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.7"
      env: TOXENV=py37-cython
    - python: "3.8"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py37-cython

    # Meta
    - python: "3.8"
      env: TOXENV=flake8
    - python: "3.8"
      env: TOXENV=manifest
    - python: "3.8"
      env: TOXENV=docs
    - python: "3.8"
      env: TOXENV=mypy


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
